### ISSUE TITLE
Test Failures on 1.8 & master

### ISSUE THREAD

**Issue by kezabelle** [carljm/django-model-utils#160]
Under `1.8` and `master` tests, travis is currently failing on `add_timeframed_query_manager` raising `AppRegistryNotReady` ([sample job](https://travis-ci.org/carljm/django-model-utils/jobs/48444193)).
I think providing an `AppConfig` and moving the signal registration to the `ready` ought to work, with a `if not hasattr(django, 'setup')` check around the old usage in `models.py`, though I'm perplexed as to why that isn't also a problem under 1.7.

Additionally I *think* the `select_subclasses(ModelCls, ...)` functionality may be broken under `master` at least--though the tests don't show such--as I believe `parent_model` has been dropped, possibly in favour of `model`. 
I ought to be able to fix that, though the timeframed blocker would prevent my testing the entire build for success.

**Comment by carljm** [comment]
PR #161 should fix both, I think. (The select-related one was pretty simple so I just did it while I was in there.) Let's see what Travis says...

**Comment by carljm** [comment]
Fixed with merge of #161
