### ISSUE TITLE
Makemigrations unable to detect polls

### ISSUE THREAD

**Issue by pankajbhanu** [carljm/django-model-utils#167]
I am following the official tutorial for django. When i run python manage.py makemigrations polls, it get app polls not found. what can be the reason this. I am using django 1.8 and python 2.7

**Comment by orgkhnargh** [comment]
Quote from official tutorial:
> Edit the `mysite/settings.py` file again, and change the `INSTALLED_APPS` setting to include the string 'polls'. So it’ll look like this:
> ```python
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',
)
```

https://docs.djangoproject.com/en/1.8/intro/tutorial01/#activating-models

**Comment by pankajbhanu** [comment]
i followed the tutorial sequentially and changed the settings.py to include 'polls'. But still i am getting the same error. 
"App 'polls' could not be found. Is it in INSTALLED_APPS? "
btw i am using online ide c9.io

**Comment by carljm** [comment]
This doesn't seem to be related to django-model-utils. You might want to seek help on the django-users mailing list or the #django IRC channel on FreeNode.
