### ISSUE TITLE
get_all_related_objects deprecation warning with Django 1.8

### ISSUE THREAD

**Issue by pmdarrow** [carljm/django-model-utils#184]
https://github.com/carljm/django-model-utils/blob/master/model_utils/managers.py#L103 raises the following deprecation warning in Django 1.8: 

```django.utils.deprecation.RemovedInDjango110Warning: 'get_all_related_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'```

**Comment by hellvix** [comment]
I got the same warning on 1.9.
