### ISSUE TITLE
QuerySet._clone() no longer has 'klass' parameter. [Django 1.9]

### ISSUE THREAD

**Issue by jarekwg** [carljm/django-model-utils#190]
https://github.com/django/django/commit/4c3bfe9053766d378999d06ec34ee5fd4e39f511#diff-5b0dda5eb9a242c15879dc9cd2121379R1043

This breaks PassThroughManager, amongst other things.

**Comment by carljm** [comment]
Thanks for the report. I don't really use `model-utils` anymore (aside from `Choices`), so I'm not likely to find time to update this stuff for Django 1.9. I'll gladly review and merge pull requests, though. (And if anyone wants to take over maintenance of `django-model-utils`, I am more than willing to hand it off.)

**Comment by jarekwg** [comment]
I was just made aware of QuerySet.as_manager(), introduced in Django1.7. It makes PassThroughManager redundant. If you like I can submit a pull request that either
-removes PassThroughManager entirely (dropping support for Django<1.7)
-raises exception when trying to use PassThroughManager for Django>=1.9 (and maybe deprecation warning for Django>=1.7)
-overrides PassThroughManager's constructor to return QuerySet.as_manager() for Django>=1.7

**Comment by carljm** [comment]
Since Django 1.7 is now the minimum version with upstream security support, I'm happy for model-utils master to bump to 3.0alpha and drop support for everything prior to 1.7, and remove PassThroughManager.

**Comment by jarekwg** [comment]
Cool. Made a fork, will make pull request in a coupla days.
