### ISSUE TITLE
Setting help_text for model fields

### ISSUE THREAD

**Issue by getup8** [carljm/django-model-utils#193]
Is there a simple way to set, say, help_text for the `start` and `end` fields in a subclass of TimeFramedModel?

**Comment by orgkhnargh** [comment]
[TimeFramedModel](https://github.com/carljm/django-model-utils/blob/master/model_utils/models.py#L31) is an ordinary model with `start` and `end` fields defined. You can define those fields yourself including desired help_text. You don't even need to subclass the TimeFramedModel in this case.

Also you can write your own TimeFramedModel with help_text to subclass in case your project requires multiples timeframed models with same help_text:

```python
class MyTimeFramedModel(models.Model):
    """
    An abstract base class model that provides ``start``
    and ``end`` fields with custom help text.
    """
    start = models.DateTimeField(_('start'), null=True, blank=True, 
                                 help_text='Custom help text.')
    end = models.DateTimeField(_('end'), null=True, blank=True,
                               help_text='Another custom help text.')

    class Meta:
        abstract = True
```

**Comment by getup8** [comment]
Makes sense, thanks @orgkhnargh For my use case, it's fine to actually do either of those, I was just seeing if there was a way where I wouldn't have to redefined those fields (but in this case it's quite trivial so is fine). Anyway, appreciate it.
