### ISSUE TITLE
SubfieldBase has been deprecated. Use Field.from_db_value instead.

### ISSUE THREAD

**Issue by hellvix** [carljm/django-model-utils#200]
/python3.4/site-packages/django/db/models/fields/subclassing.py:22: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  RemovedInDjango110Warning)

I haven't even implemented the package in my code. What does that mean?

**Comment by carljm** [comment]
What command are you running that gets that warning?

What version of Django do you have installed?

What version of django-model-utils do you have installed?

Most recent django-model-utils only uses SubfieldBase in one place, in the tests. And even then only on Django < 1.9, where I don't think it should raise a visible warning. And the django-model-utils tests shouldn't run (or even be imported) when you run your project's tests (unless you're using Django 1.5 or earlier).

So once again I have to doubt that this is related in any way to django-model-utils. More likely it's related to some other package you are using, or to code in your own project, that is using SubfieldBase, which now raises a deprecation warning on Django 1.9, which you just upgraded to.

**Comment by hellvix** [comment]
1) manage.py runserver
2) Django 1.9 (Python 3.4.3)
3) django-model-utils==2.4

Doesn't runserver run 'test' itself?

**Comment by carljm** [comment]
Runserver does not run test. And even if you run test, it won't run (or import) django-model-utils tests.

Based on the information you provided, I'm 99.9% sure this issue is another one related purely to your Django 1.9 upgrade and some other code in your project or some other dependency. It is not related to django-model-utils.

**Comment by hellvix** [comment]
Yeah, you are right. I uninstalled the app and the problem persisted. I will figure out what is it and update the post. Thanks for the fast replies :)
