### ISSUE TITLE
Remove PassThroughManager from docs add suggestions from changelog

### ISSUE THREAD

**Issue by jChapman** [carljm/django-model-utils#201]
I found django-model-utils because of the PassThroughManager, and the latest version of the docs (https://django-model-utils.readthedocs.org/en/latest/managers.html#passthroughmanager) still mentions it. 

Had to search through this repo to find out that it was recently removed.

I suggest replacing the docs with the suggestions you gave in the changelog (CHANGES.rst)

**Comment by carljm** [comment]
Sorry about that. I handled the `PassThroughManager` removal poorly in a number of ways! Docs updated now.

**Comment by jChapman** [comment]
No problem, thanks for the quick update.
