### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by gustavi** [carljm/django-model-utils#203]
Please, could you make a release 'pypi package) to support Django 1.9 ?

**Comment by carljm** [comment]
Version 2.4 was released on Dec 2 2015, and its tests passed against Django 1.9 on Travis. Are you seeing a specific problem with v2.4 and Django 1.9?

**Comment by gustavi** [comment]
Version 2.1.1a1 works. My bad but no GH release for this version.

**Comment by carljm** [comment]
2.1.1a1 isn't in the GH releases list because it isn't tagged, because it wasn't a real release, just a development version. Why would you use 2.1.1a1 instead of a more recent real released version like 2.4?
