### ISSUE TITLE
[tests] timestamp resolution is too low on Windows, causes tests to fail

### ISSUE THREAD

**Issue by kichawa** [carljm/django-model-utils#206]
sqlite3
django.1.8

https://github.com/carljm/django-model-utils/blob/master/model_utils/tests/tests.py#L163

Datetime is equal. Resolution of time is too low, for example: 2016-01-28 13:13:27.675000+00:00.

There could be greater than or equal to?!

**Comment by carljm** [comment]
So you are seeing failures in this test because the two timestamps are equal? I've never seen that, locally or on CI. What OS are you on?

**Comment by kichawa** [comment]
Yes. Both timestamps are equal. Locally. Sqlite3. Unfortunately Windows 10.

**Comment by carljm** [comment]
Yeah, I'd guessed it was probably a Windows issue. I'm not sure how to address that. Making it "greater than or equal to" really defeats the purpose of the entire test (since the point is that the changed timestamp was updated when the name was changed, and is no longer the same as the created timestamp.)

**Comment by carljm** [comment]
I'd accept a PR to skip that test on Windows, barring a more creative solution.

**Comment by romgar** [comment]
@carljm Why not using `freezegun` (https://github.com/spulec/freezegun) for this kind of test?

I think that's the right way to test anything involving `now()`, as we precisely control this value by this efficient (and reliable, I'm using it for a long time now) `freezegun` mocking.

That would 1/ make the tests cleaner and 2/ probably eliminate this kind of issue.

**Comment by carljm** [comment]
I'm fine with adding freezegun as a test-only dependency and modifying the timestamp tests to use it.

**Comment by romgar** [comment]
I will create a PR for that then!
