### ISSUE TITLE
FieldTracker and DecimalFields

### ISSUE THREAD

**Issue by apollodatasolutions** [carljm/django-model-utils#216]
Seems like there is an issue with FieldTracker and DecimalFields in Django.  I changed two fields on a model instance and printer the trackers.changed() and I got this output:

`{'built_far': Decimal('0.970'), 'description': u'', 'cross_street': u'test cross', 'residential_far': Decimal('2.430')}
`

The two Decimal field did not have any changes to them.

**Comment by apollodatasolutions** [comment]
Oh, I think it issue specifically is that the Decimal value ends in a zero, i.e. 0.970, but the code seems to boil it down to 0.97, which is different from 0.970 - hence it sees it as changed.

**Comment by apollodatasolutions** [comment]
Actually, this was our bad, there was a hidden conversion between Decimal and Float by a data cleanup layer.  So not an issue with django-model-utils.

**Comment by carljm** [comment]
Thanks for the follow-up!
