### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by mjschultz** [carljm/django-model-utils#217]
It [looks like](https://code.djangoproject.com/wiki/Version1.10Roadmap) Django 1.10a1 is slated for next month. Would it be possible to get a release that includes the removal of features deprecated in 1.10?

I think the relevant existing changes were in https://github.com/carljm/django-model-utils/pull/207 and https://github.com/carljm/django-model-utils/pull/208.

Thanks!

**Comment by carljm** [comment]
Released 2.5.

**Comment by mjschultz** [comment]
Thanks, my build is much cleaner now!
