### ISSUE TITLE
How can compare date vs TimeStampedModel?

### ISSUE THREAD

**Issue by thanhngvpt** [carljm/django-model-utils#223]
Hello Sir.
In my django app how can i filter by date in TimeStampedModel fields?
I am tried 
`from datetime import date

date = date(2016, 5, 22)

Order.objects.filter(created_attr__date=date)
`

But failed with error "Cannot resolve keyword 'created_attr' into field"
Please tell me how to resolve?
Many thanks

**Comment by carljm** [comment]
Hi! Where did you get `created_attr` from? The field on `TimeStampedModel` is called just `created`, so the query would be `.filter(created__date=date)`.

**Comment by thanhngvpt** [comment]
resolved, thank man

**Comment by thanhngvpt** [comment]
Hello @carljm. This is still issue with me, some day ago i resolved my issue is i want to  get query from date to date, so i make query by `Order.objects.filter(created__range=(start_date, end_date))` But to day i try to make a more simple query by `Order.objects.filter(created__date=today)` as you sussgested above but it make an error "Unsupported lookup 'date' for AutoCreatedField or join on the field not permitted."
Please help me how to resolve? 
Many thanks.
