### ISSUE TITLE
Initial value of AutoLastModifiedField

### ISSUE THREAD

**Issue by slomo** [carljm/django-model-utils#224]
I was wondering whether the initial value of AutoLastModifierField shouldn't be null after calling save for the first time, because the model wasn't modified yet. It was only created.

**Comment by romgar** [comment]
Hi @slomo!

I think it's a better idea to stick with a similar Django logic with `auto_now` and `auto_now_add` field parameters (https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.DateField).
Generally, people are already used to that.
And you could see "created" as a specific situation which is "modified for the first time" :-)

**Comment by romgar** [comment]
Closing it for now, as I don't think it's a good idea to make this change (re my previous comment).

**Comment by slomo** [comment]
Thanks for your response. Since I never the less needed the feature I implemented it in my own reference [mixin](https://github.com/liqd/euth_wagtail/blob/master/euth/contrib/base_models.py#L6).
