### ISSUE TITLE
Setting the default on MonitorField

### ISSUE THREAD

**Issue by stantond** [carljm/django-model-utils#226]
Looking at `MonitorField`, the default will always be `django.utils.timezone.now`:

```
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('default', now)
```

However, when creating a new object, could it make more sense for this to be `null` in some common situations? For example, in the docs, `published_at = MonitorField(monitor='status', when=['published'])` would put the created `datetime` in `published_at`, even when `status` has never been set to `published`.

**Comment by carljm** [comment]
Sure, that's why the code you pasted uses `setdefault`, not a normal dict-set; so that you can override. By default `MonitorField` is non-nullable, if you want a nullable `MonitorField` that defaults to null, just say `mymonitor = MonitorField(monitor=..., null=True, default=None)`

**Comment by stantond** [comment]
Sorry, misunderstood it, thanks!
