### ISSUE TITLE
Python 3.5 Support?

### ISSUE THREAD

**Issue by froomzy** [carljm/django-model-utils#228]
Hi there,

We are looking to upgrade our python version from 3.4 to 3.5, and I have the fun job of checking compatibility of packages. I see that django-model-utils still only supports up to 3.4. Is there any particular reason for this? Any thing that would stop us from using this with 3.5?

Cheers.

**Comment by kezabelle** [comment]
I don't think there's anything specifically blocking Python 3.5 support: The [most recent CI build](https://travis-ci.org/carljm/django-model-utils/builds/144567101) executed successfully for 3.5 on Django 1.8 and 1.9. Probably its just a question of the Trove classifiers and README not having been updated.

**Comment by carljm** [comment]
Fixed in 535fe46702fd4d5bdff458637237e9103e5851d1

**Comment by froomzy** [comment]
Yeah, after posting this, and then moving onto the next, it occurred to me that I could look at Travis/Tox files and see what packages were executing against, and that would most likely answer my questions.

Thanks for the answer though.
