### ISSUE TITLE
Mind to bump pypi due to soon Django 1.10 release?

### ISSUE THREAD

**Issue by pySilver** [carljm/django-model-utils#229]
Hi!

Please bump pypi version. Django 1.10 is almost out.

Thanks!

**Comment by toxinu** [comment]
I agree, some bug fixes have been merged into master for Django 1.10 (#220, for example) and not released on Pypi.

**Comment by carljm** [comment]
The tests don't currently pass on Django 1.10 and I don't have time to investigate or fix it. I don't mind making a release with the fixes that are in so far, but it'll remain officially not-supported on Django 1.10.

**Comment by carljm** [comment]
2.5.1 is released.
