### ISSUE TITLE
requirements.txt does not reflect reality

### ISSUE THREAD

**Issue by Germano0** [carljm/django-model-utils#231]
File `requirements.txt` file does not reflect reality. Indeed tox,sphinx,twine seem to not be required, as you can see from setup.py

**Comment by carljm** [comment]
Setup.py includes the runtime dependencies. Requirements.txt includes the development dependencies. I could add a comment to the file clarifying that, or add -dev to the file name.

**Comment by Germano0** [comment]
Mmh okay. Do you think that the requirements mentioned in the spec file at
https://bugzilla.redhat.com/show_bug.cgi?id=1365782#c4
are okay for django-model-utils being shipped into Fedora repositories?

**Comment by carljm** [comment]
Sure, though I don't think that `pythonX-devel` or `pythonX-setuptools` should actually be required at runtime. Setuptools would be required to run `setup.py` (and thus to generate the rpm), but `setup.py` is not used at runtime, and no other part of model-utils imports `setuptools` or `pkg_resources`. Not sure why `pythonX-devel` would be needed, but I'm not very familiar with Fedora packaging.

Django is the only runtime dependency for model-utils.

**Comment by Germano0** [comment]
`pythonX-devel` and `pythonX-setuptools` are mandatory to build any Python package.
Thank you for your explanation.
Have a nice day
