### ISSUE TITLE
FieldTracker failing with Django 1.10

### ISSUE THREAD

**Issue by jarekwg** [carljm/django-model-utils#232]
I know you're already aware the dj110 tests don't pass, but thought I'd leave an open ticket for this, with (hopefully relevant) info I've come across.

I might also have a go at tackling this over the weekend, but no promises. ;)

So my issue since upgrading to dj110 and updating to model-utils 2.5.1:
Creating a model instance via a `DjangoModelFactory` (in my case using factory-boy), causes the initialised fields to come up on the `FieldTracker` as having changed in successive saves. `DjangoModelFactory()` calls the model's `.save()` method up to three times in some cases, so with this bug, a post_save handler will think the field has changed numerous times and will register fields as having changed multiple times, instead of not mentioning anything since the fields were set on init. This appears to happen both with FK fields and regular ones, so no discrimination there. factory-boy hasn't changed recently, so I suspect the problem lies with model-utils' `FieldTracker`, but I might be wrong.

**Comment by jarekwg** [comment]
So after a bit of digging, it seems dj110 is marking all model fields as deferred by default..

ie `instance._deferred_fields` seems to now contain a list of all the model fields when in the past it was just `[]`.

Will keep digging.

**Comment by brianmay** [comment]
Any chance of a new release with this fixed?

Thanks
