### ISSUE TITLE
Recursion error with double MonitorField and defer()/only() usage

### ISSUE THREAD

**Issue by romgar** [carljm/django-model-utils#241]
Using two `MonitorField` in a same model generates a recursion error as soon as we use `only()` or `defer()` on that model, but only with Django `1.10+`.

I will create a PR to demonstrate the issue.

**Comment by carljm** [comment]
Thanks @romgar for the report and failing tests! Unlikely that I will have time to work on a fix for this soon, but I'd be happy to review and merge a fix if someone comes up with one.

**Comment by romgar** [comment]
Issue fixed by PR #242!
