### ISSUE TITLE
Split tests in several files and remove them from the package distribution

### ISSUE THREAD

**Issue by romgar** [carljm/django-model-utils#244]
Hi @carljm ,

I think it would be better to split the tests in several files.

It would:
- Improve test readability,
- Reduce merge conflicts between PRs.

I also think that's not really useful to distribute the tests with the python package, they could live outside of the `model_utils` folder.

What do you think?

**Comment by carljm** [comment]
I'm OK with both of those changes; +1 on splitting into smaller test files, +0 on moving outside the `model_utils` folder.

**Comment by romgar** [comment]
Moving them outside of the `model_utils` folder requires a bit of work to update the test run. I will first deal with all the current issues/PRs, which are more important than this.
