### ISSUE TITLE
Problem with STATUS in administration view. Show only first status.

### ISSUE THREAD

**Issue by error0608** [carljm/django-model-utils#251]
Having a model like this:
```
class ArticleAbstractModel(StatusModel, TimeStampedModel, TimeFramedModel):
    STATUS = Choices('published', 'draft')

    objects = LiveQuerySet.as_manager()

    class Meta:
        abstract = True
```

```
class ArticleModel(ArticleAbstractModel):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    body = SplitField()
```
When I open this model (ArticleModel) on administrator page, it show me all objects with status == 'published'. Object with 'draft' status i don't see. But if do like this:
`STATUS = Choices('draft', 'published')`
System show me object only with 'draft' status.

Django == 1.10.5
django-model-utils == 2.6

**Comment by romgar** [comment]
Hi @error0608 !

Can you show be the code behind `LiveQuerySet` class? Can you also copy paste your Admin model, if you customised it?

**Comment by error0608** [comment]
Hi, @romgar
```
class LiveQuerySet(QuerySet):
    def live(self, statuses=['published']):
        today = timezone.now()
        return self.filter(status__in=statuses). \
            filter(Q(start__lte=today) | Q(start__isnull=True)). \
            filter(Q(end__gte=today) | Q(end__isnull=True))
```
```
@admin.register(ArticleModel)
class NewsAdmin(admin.ModelAdmin):
     pass
```

**Comment by romgar** [comment]
@error0608 Thanks! I managed to reproduce it, I will have a deeper look.

**Comment by romgar** [comment]
It seems that the Django Admin is using the `default_manager` to display the list of items in a model admin page.

But `StatusModel`, through the `add_status_query_managers` function, is adding custom managers (one per status), and these `add_to_class` calls seems to change the default manager.

I tried to save the default manager before the calls to `add_to_class`, and restore it after, it seems to solve this admin issue and keep the default manager.
Not sure that's the most elegant way to solve it though.

```
def add_status_query_managers(sender, **kwargs):
    """
    Add a Querymanager for each status item dynamically.

    """
    if not issubclass(sender, StatusModel):
        return

    # First, get current manager name...
    default_manager = sender._meta.default_manager

    for value, display in getattr(sender, 'STATUS', ()):
        if _field_exists(sender, value):
            raise ImproperlyConfigured(
                "StatusModel: Model '%s' has a field named '%s' which "
                "conflicts with a status of the same name."
                % (sender.__name__, value)
            )
        sender.add_to_class(value, QueryManager(status=value))

    # ...then, put it back, as add_to_class is modifying the default manager!
    sender._meta.default_manager_name = default_manager.name
```

@carljm any feedback?

**Comment by carljm** [comment]
Seems OK. I suspect it only works on recent Django versions, though. (The bug may also only exist on recent Django versions, the way the default-manager is determined was changed in a recent release).

**Comment by error0608** [comment]
Maybe check version? This bug not exist in 1.9 Django

**Comment by romgar** [comment]
You are right @carljm , only works in `1.10`, and previous versions don't have this issue. PR submitted.
