### ISSUE TITLE
Add a pull requests template

### ISSUE THREAD

**Issue by browniebroke** [carljm/django-model-utils#254]
To avoid contributors missing some steps when submitting a change, I suggested to add a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) to this project.

Inspirations:
* [Dredd](https://github.com/apiaryio/dredd/blob/master/.github/PULL_REQUEST_TEMPLATE.md)
* [Celery](https://github.com/celery/celery/blob/master/.github/PULL_REQUEST_TEMPLATE)

We could link to the guidelines for contributing, but Github does it automatically at the moment when opening a PR or an issue:
![screen shot 2017-01-10 at 10 12 27](https://cloud.githubusercontent.com/assets/861044/21802359/5543b246-d71d-11e6-802d-032ac96dbd5e.png)

I personally quite like the "What didn't I forget?" checklist, especially around documentation, tests and other housekeeping like changelog.

**Comment by romgar** [comment]
I think that's a good idea. 

We could have a checklist, but also some sections, like "Problem you want to solve", "Solution", ...

For a new issue, something like:
```
Problem
---
Explain the problem you encountered.

Environment
---
Python version: 
Django version: 

Other libraries used, if any:

Code examples
---
Give code example that demonstrates the issue, or even better, write new tests that fails because of that issue.
```

For a new PR, something like:
```
Problem
---
Explain the problem your merge request is fixing (add the link to the related issue(s), if any).

Solution
---
Explain the solution that has been implemented, and what has been changed.

Commandments
---
- [ ] Write PEP8 compliant code,
- [ ] Cover it with tests,
- [ ] Update README file to describe the changes, and quote according issue with `GH-<issue_number>`,
- [ ] Pay attention to backward compatibility, or if it breaks it, explain why,
- [ ] Update documentation (if relevant).
```
