### ISSUE TITLE
Remove tests from the package distribution

### ISSUE THREAD

**Issue by browniebroke** [carljm/django-model-utils#258]
## Problem 

Originally raised in #244, which was tracking the split of tests, but now closed. I'm in favour of getting the tests excluded from the distribution, I personally think testing code should not be present on Production machines. However, they seem to be needed to be able to package for RPM (see #230 @Germano0 ?)

The official packaging doc [suggests it](https://packaging.python.org/distributing/#packages), but it doesn't state it clearly.

Testing code is around 2/3 of the code in this repo (1031 lines vs. 2369 from a quick estimate), so that would also make the distribution lighter.

**Comment by romgar** [comment]
I'm +1 to remove them from the distribution. I guess that, if we remove the test-related arguments in `setup.py` and exclude the `models_utils.tests` folder, it should be enough.

And ideally, it would have even been better to move the `tests` folder outside of the `model_utils` folder, and not even have to exclude anything in `setup.py`.
