### ISSUE TITLE
i followed the tutorial on django girls . This is the error i get . python manage.py makemigrations blog App 'blog' could not be found. Is it in INSTALLED_APPS? 

### ISSUE THREAD

**Issue by tolutweety** [carljm/django-model-utils#266]
## Problem

Explain the problem you encountered.

## Environment

- Django Model Utils version:
- Django version: 
- Python version: 
- Other libraries used, if any:

## Code examples

Give code example that demonstrates the issue, or even better, write new tests that fails because of that issue.

**Comment by romgar** [comment]
Hi @tolutweety !

This repository should treat only about `django-model-utils` package issues.
For get some help for the Django Girls tutorial, https://gitter.im/DjangoGirls/tutorial is a good starting point, and I just saw that you went there :+1:
