### ISSUE TITLE
Inheritance fails with Django 1.11

### ISSUE THREAD

**Issue by nakato** [carljm/django-model-utils#269]
## Problem

Inheritance fails with Django 1.11.
When I expect a child object, I always receive the parent.

## Environment

- Django Model Utils version: master
- Django version: 1.11
- Python version: 2.7.13
- Other libraries used, if any:

## Code examples

I hit this issue with Pinnax/Symposion, however it appears to be reproducible by modifying tox to run against 1.11 as I see asserts expecting ChildClass but getting ParentClass.

I was able to track the issue down to Django commit f3b7c059367a4e82bbfc7e4f0d42b10975e79f0c

I haven't been able to pinpoint what about the patch causes this issue yet however.

**Comment by nakato** [comment]
I've tracked it down to: https://github.com/django/django/commit/f3b7c059367a4e82bbfc7e4f0d42b10975e79f0c#diff-5b0dda5eb9a242c15879dc9cd2121379L1074

`_fetch_all` now calls `_iterable_class(self)`, instead of `iterator()`

This means model_utils.manager.InheritanceQuerySetMixin:iterator is not getting called there, leading to some woes.

**Comment by robertobarreda** [comment]
#270

**Comment by carljm** [comment]
Fixed with merge of #270
