### ISSUE TITLE
Need new maintainer

### ISSUE THREAD

**Issue by carljm** [carljm/django-model-utils#272]
I am no longer able to keep up with maintenance of django-model-utils. If someone can be found who is willing to take on maintenance, I will happily hand over the keys. Model-utils is pretty low-churn at this point; maintenance (at minimum) just means responding to infrequent bug reports (not necessarily fixing them yourself), reviewing and merging PRs, and issuing occasional releases.

If no new maintainer can be found, I will update the README to prominently note that the project is unmaintained.

cc existing repo collaborators @romgar @kezabelle @treyhunner

**Comment by jpic** [comment]
Perhaps it's time to start contributing some features upstream ?

Otherwise, there's jazzband, you might already have heard of it.

**Comment by carljm** [comment]
I don't think the features in django-model-utils are well-suited for merging into Django core.

Jazzband is a cool idea though! I made an inquiry there: https://github.com/jazzband/roadies/issues/52

**Comment by carljm** [comment]
I am transferring the project to jazzband. Any existing contributors who would like to continue helping with maintenance are welcome to join the jazzband org and contribute there! Thanks everyone for all your contributions to django-model-utils.

**Comment by jpic** [comment]
> I don't think the features in django-model-utils are well-suited for merging into Django core.

Is there already something like select_subclasses in django ?

I don't find model inheritance so useable without select_subclasses, do you ?

**Comment by carljm** [comment]
No, Django core doesn't have a `select_subclasses` equivalent. There are several different third-party implementations of it with different performance characteristics, and last time I saw a comparison it wasn't clear the one in model-utils is best (though it depends somewhat on load characteristics).

**Comment by jpic** [comment]
Perhaps it would be useful to open a debate about it and join forces to add the best implementations in Django itself because otherwise model inheritance is not very useful /imho/.

Thanks for maintaining this package all these years.

With <3 from POITOU CHARENTE !

**Comment by treyhunner** [comment]
Catching up on the conversation. I haven't had time or incentive to maintain this project (or other open source Django projects) in recent years.

I think the move to jazzband was a wise one. 👍 I've found this project very valuable over the years. 💗

**Comment by carljm** [comment]
Thanks @jpic! I don't have time/energy/motivation to shepherd a discussion about adding subclass queries to Django core (among other reasons, because I am not sure that model inheritance is a pattern Django should encourage). But anyone who wants to kick off and shepherd such a conversation is welcome to draw on model-utils code, of course!
