### ISSUE TITLE
Can't use PassThroughManager with a subclass of GeoQuerySet and InheritanceQuerySet

### ISSUE THREAD

**Issue by johnwoltman** [carljm/django-model-utils#88]
I am sorry to post this as an issue because it is more of a support question (I think).

My understanding of PassThroughManager is that I should be able to mix two QuerySet-derived classes into one.  For example, I'd like to have a Manager that uses InheritanceManager _and_ GeoManager, because my models inherit from a common concrete model and have geospatial data.

The only way I can make it work the way I want is by changing InheritanceQuerySet to inherit from GeoQuerySet instead of the vanilla QuerySet.  Is that the correct way to do this?  I feel like I shouldn't be modifying code django-model-utils.  The old "from_manager" function seems closer to what I need, but it's been removed from model-utils.

**Comment by romgar** [comment]
I don't think this issue is still relevant, as `PassThroughManager` has been removed from `django-model-utils` in version `2.4`.

**Comment by romgar** [comment]
I close it for now. Feel free to reopen if you think it makes sense.
